# pre-commit 1.1.0 is required for `exclude`
# however `minimum_pre_commit_version` itself requires 1.15.0
minimum_pre_commit_version: "1.15.0"

repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: no-commit-to-branch
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.23.1
    hooks:
    - id: pyupgrade
      args: [--py36-plus]
-   repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/PyCQA/isort
    rev: '5.9.3'
    hooks:
    - id: isort
      additional_dependencies: [toml]
-   repo: https://github.com/PyCQA/flake8
    rev: '3.9.2'
    hooks:
    - id: flake8
      additional_dependencies: [
        flake8-bugbear>=20.3.2,
        flake8-logging-format
      ]
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
