# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Cache pre-commit
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pre-commit
          ~/.cache/pip
        key: ${{ runner.os }}-cache
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies & package
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U pytest pre-commit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m pip install .
    - name: Setup pre-commit
      run: pre-commit install --install-hooks
    - name: Test with pytest
      run: pytest
